version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: conda
      requirements: environment.yaml  # Install with conda using your environment.yaml

sphinx:
  configuration: docs/conf.py

