version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

install:
  - method: pip
    path: .

# python:
#   install:
#     - requirements: requirements.txt
#     - method: pip
#       path: .

sphinx:
  configuration: docs/conf.py
