version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
    - conda:
        environment: environment.yaml

  jobs:
    post_install:
      - python -m pip install --upgrade --no-cache-dir pip setuptools
      - python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext

sphinx:
  configuration: docs/conf.py

