package:
  name: xindices
  version: "1.3.6"

source:
  path: .
  # files:
  # - README.md


extra:
  channels:
    - conda-forge


build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.11
    - setuptools         
    - numpy >=2.0  
    - xeofs >2.2.3
    - xesmf >=0.7   

  run:
    - python >=3.11
    - xarray
    - numpy >=2.0
    - dask
    - xesmf >=0.7
    - matplotlib
    - cartopy
    - xeofs >2.2.3

run_constrained:
 - numpy >=2.0

test:
  imports:
    - xIndices
  # requires:
  # - esmpy
  # - pip 

about:
  home: https://github.com/JiveshDixit/xIndices
  license: MIT
  summary: "A xarray based module for computing SST trends and SST variability modes and other atmospheric variability modes"
  description: |
    A xarray based module for computing SST trends, SST variability modes and other atmospheric variability modes
  author: Jivesh Dixit
  author_email: jiveshdixit@cas.iitd.ac.in

extra:
  recipe-maintainers:
    - JiveshDixit
